### ISSUE TITLE
Is there a way to retain dimming setting for groups?

### ISSUE THREAD

**Issue by garyhooper** [tagyoureit/hubitat-luxor#3]
When I turn on a group, it sets those lights to be 100%.  If I subsequently set the dimming to 50%, turn off the lights, and turn them back on, they are now back at 100%.  Is there a way to retain the dimming value?

**Comment by tagyoureit** [comment]
This is what themes are for. You can turn on a theme and have the lights come on with different intensity (and colors). You need to set these up in the Luxor app and they will appear as momentary switches in the hub.

**Comment by garyhooper** [comment]
Thanks. By the way, thank you for this integration. It is a significant improvement over what FX Luminaire provides for their product.
