### ISSUE TITLE
Luxor themes cannot be controlled from Rule Machine

### ISSUE THREAD

**Issue by marcaronson408** [tagyoureit/hubitat-luxor#5]
**Describe the bug**
Luxor theme buttons do not show up in Rule Machine, as discussed in [this Hubitat Community thread](https://community.hubitat.com/t/how-to-access-custom-action-for-a-momentary-button/55022).  

Post 1 describes the problem.

Post 8 talks about how the button capability has been deprecated.

Post 9 provides the solution, which is to add the following line to the theme driver: capability "Actuator"

It would be very helpful if you added this to the code in this repo so that those getting it via the Hubitat Package Manage don't have to rediscover and fix this problem.

Thank you for considering this change.

Marc

**Comment by tagyoureit** [comment]
Added.  Thanks for bringing the other thread to my attention.
