### ISSUE TITLE
Suggested enhancement for multi-controller environment

### ISSUE THREAD

**Issue by marcaronson408** [tagyoureit/hubitat-luxor#6]
Greetings and thank you for this fantastic driver -- it is really helpful!

I have 3 controllers. All 3 controllers have the same set of themes programmed in them, as the property lighting required more then 1 controller.  An example of one of the themes that is in all 3 controllers is called "Morning exercise lighting".

As expected, this creates a child device under each controller named "Morning exercise lighting".

The challenge is when one is trying to activate that theme in Rule Machine. All 3 "devices" named "Morning exercise lighting" show up in the rule machine list (see screenshot).

It would be very helpful if the child devices had some sort of prefix on the name that helped to differentiate which controller it was on.

Thank you for considering this change.

Marc

![image](https://user-images.githubusercontent.com/6984947/217018150-c5cfbf44-714e-4cc9-90cb-e7bdc21fc571.png)

**Comment by tagyoureit** [comment]
I'll take a look at this later.  But in the meantime you can go and rename them yourself in Hubitat before you view them in Rule Machine.

**Comment by marcaronson408** [comment]
Thank you for the suggestion. Unfortunately, when I tried that this morning the name was reset to the original name after a couple of minutes. If I remember correctly, a refresh from the controller runs every 5 minutes or so, and it appears that results in the name being changed back to the original...

Thank you again for considering the change.

Marc

**Comment by tagyoureit** [comment]
Can you pull this branch down and try the changes: https://github.com/tagyoureit/hubitat-luxor/tree/multi-controller

Unfortunately, I don't have access to either my Hubitat nor my Luxor so flying a bit blind here.  You only need the [3 files](https://github.com/tagyoureit/hubitat-luxor/compare/master...multi-controller) as listed in the last pull.

There should be a new input value for a controller label on the setup page.  Leave it blank and it will ignore the name.  Or add a name and it will be added to the themes (I only did this for the theme atm; but let me know if it works and if you need it for the groups).

**Comment by marcaronson408** [comment]
Can I use that link with HPM, or do I need to copy-and-paste the RAW view
of the code into the hub?

Marc

**Comment by marcaronson408** [comment]
After digging around a bit it looks like I should copy-and-paste the code
for these 3 files -- luxor-controller.src, luxor-theme.src and
luxor.groovy. The first 2 are code for device drivers; the last one is the
app.

Is this correct? If so, I will proceed, thanks!

**Comment by marcaronson408** [comment]
I went ahead a gave it a try. Got the error shown in the screenshot below
when saving the device driver "Luxor Controller"...

[image: image.png]

**Comment by marcaronson408** [comment]
Looks like a missing "{" at the end of the "if" on line 313. Giving that a
try

Marc

**Comment by tagyoureit** [comment]
Sorry - had to step out for a bit.  Unfortunately, you can't email images to these issues (as above they only show up as `[image: image.png]`).  You'll need to log into the web site here and upload any images.

**Comment by marcaronson408** [comment]
Here is the screenshot of the error I got when trying to save device driver "Luxor Controller". Adding the open brace at the end of the "if" statement seems to solve this.

![image](https://user-images.githubusercontent.com/6984947/217150715-c82161e6-0cf5-4ef3-9f7b-5b4f694d17d3.png)

**Comment by marcaronson408** [comment]
After updating the 2 drivers and the app, I get the following error when trying to run the Luxor app

![image](https://user-images.githubusercontent.com/6984947/217150867-2d175693-339c-4753-aab7-10ce446dd305.png)


Here are the logs

![image](https://user-images.githubusercontent.com/6984947/217150922-f0bd96ed-6e8a-46aa-9563-e6c04a71d2b8.png)

**Comment by tagyoureit** [comment]
The missing bracket was higher up (line 279).  You can grab the latest version of the file and try it.

**Comment by marcaronson408** [comment]
I gave it as try -- when I try to run the Luxor app I get the error, below.

FYI in case it matters -- I have not removed my existing Luxor app and devices.

Marc

<img width="565" alt="image" src="https://user-images.githubusercontent.com/6984947/217316378-e049690f-4f44-4c61-9906-3c045108ccb0.png">

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/6984947/217316558-3abe591e-4169-4914-a7fe-cdf3d6c6c25a.png">

**Comment by tagyoureit** [comment]
Ok, pull again.  (It's also been a looong time since I've touched any groovy code.)

**Comment by marcaronson408** [comment]
I appreciate the time and effort you are putting into this.

The app does not error when I run it. It identifies 1 of the 3 controllers and allows me to enter a name. I do that and wait a minute. When I look at the device, the themes all have a device name of "Luxor Theme" and the device label is blank (see screen shot). Previously the device label would have the theme names that was assigned in the Luxor app. 

No errors in the logs.

Marc

<img width="941" alt="image" src="https://user-images.githubusercontent.com/6984947/217354954-d68dc463-f9e5-4cdc-ae08-b628159f7450.png">

Screenshot of log for the luxor app

<img width="671" alt="image" src="https://user-images.githubusercontent.com/6984947/217355529-517ec357-1f89-4bbc-8ec5-92b6e0fd9be2.png">


Screenshot of log for the device where I entered the name into the app. The name I used was "L2-Pool".

<img width="919" alt="image" src="https://user-images.githubusercontent.com/6984947/217355708-17c5db78-f007-4abd-8677-ea1c5877821d.png">

**Comment by marcaronson408** [comment]
One more thing -- I only updated the Luxor app on this most recent update as it looked like that was the only file that changed, but let me know if I made a mistake.

**Comment by marcaronson408** [comment]
I have 2 different suggestions that might make this simpler.

1. Have the user enter the prefix in the driver for the parent device (the controller). The parent would then be responsible for updating the device labels.
2. alternatively, stop automatically populating the device label. Leave it blank. This means the device name, which is the name of the theme, will be as it was before, but the user can manually enter a different name for the device label. Since you aren't automatically generating this label anymore, the periodic refresh won't wipe out the manually assigned name.

The first suggestion would be nicer, as it means an updated theme name in the app will automatically propagate to Hubitat with the right prefix. I suspect the second suggestion would be the simplest to implement.

Food for thought...

Marc

**Comment by tagyoureit** [comment]
Sorry for the delay... I should be able to spend some time on this next week.  I was planning/trying to implement 1 as you have listed above.

**Comment by marcaronson408** [comment]
No worries. I appreciate what you are doing.

**Comment by tagyoureit** [comment]
Can you manually update the files again from the branch?  I tested it out and it should be working now.  After you upload the files, go back to the Apps and rerun the Luxor app.  There is a new entry for the prefix to the controller and all of the lights/themes/etc.  

If this works, I'll push the changes to the main branch which can then be updated with HPM.

**Comment by marcaronson408** [comment]
It works!

I did see one odd behavior in Rule Machine. My existing rules would still
show the old device labels in the list of actuators to act on. Simply
clicking on the list and then clicking "Update" caused all the labels in
the list to update. I am guessing this is a Rule Machine idiosyncrasy
related to the device labels changing and not caused by your code, but
thought it worth mentioning.

Thanks again for making the changes!

Marc

**Comment by tagyoureit** [comment]
Awesome!  I just pushed the code to the master branch so anyone can now update with HPM.  

And yes, any third party apps (like Rule Machine) will need to be reconfigured to pull in the new names.  That's to be expected.

**Comment by marcaronson408** [comment]
Thanks again for doing this! 

I just did a package manager update to ensure I am in sync for future updates.

Do you plan to post an update on the Hubitat thread or would you prefer that I take care of that?

Marc

**Comment by tagyoureit** [comment]
Can you post the update?  Much thanks!

**Comment by marcaronson408** [comment]
Unfortunately, I now have the problem where all the Themes in a given controller are just named "Luxor Theme", per the screenshot below. 

Group names work as expected.

Someone else is reporting the same issue. Hate to bug you about this -- thanks for any help you can provide.


![image](https://user-images.githubusercontent.com/6984947/221723695-cc5f1415-4d45-4e4c-bd44-4b4252a49063.png)

**Comment by marcaronson408** [comment]
I dug a little deeper -- the "Device label" field for themes is now blank for all themes. For groups, the "Device label" field contains the fully qualified name, ie: <prefix><group name>

![image](https://user-images.githubusercontent.com/6984947/221724572-bdb02baa-0cf2-440e-bb40-07f20c3db57b.png)

**Comment by marcaronson408** [comment]
Here is an extract from my logs that shows the theme names are coming in properly from the controller. I filtered the logs on the controller shown in the previous screenshots

![image](https://user-images.githubusercontent.com/6984947/221725253-fa3b602b-aa39-4622-b6d2-4bf6547b937c.png)

**Comment by tagyoureit** [comment]
Ugh, somehow the merge didn't happen from the other branch as planned.  Can you please pull 1.2.2 from HPM and it should fix it.

**Comment by marcaronson408** [comment]
That did it -- thanks!

Marc
